export const SET_QUERY = "WEATHER/SET_QUERY";
export const GET_CURRENT = "WEATHER/GET_CURRENT";
export const GET_WEEKLY = "WEATHER/GET_WEEKLY";
export const SET_ERROR = "WEATHER/SET_ERROR";
export const SKIP_ERROR = "WEATHER/SKIP_ERROR";
